/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct values {
	float num1;
	float num2;
	char operation;
};
typedef struct values values;

#define COMPUTE 456123789
#define COMPUTE_VERS 7

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  float * add_7(values *, CLIENT *);
extern  float * add_7_svc(values *, struct svc_req *);
#define SUB 2
extern  float * sub_7(values *, CLIENT *);
extern  float * sub_7_svc(values *, struct svc_req *);
#define MUL 3
extern  float * mul_7(values *, CLIENT *);
extern  float * mul_7_svc(values *, struct svc_req *);
#define DIV 4
extern  float * div_7(values *, CLIENT *);
extern  float * div_7_svc(values *, struct svc_req *);
#define POW 5
extern  float * pow_7(values *, CLIENT *);
extern  float * pow_7_svc(values *, struct svc_req *);
extern int compute_7_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  float * add_7();
extern  float * add_7_svc();
#define SUB 2
extern  float * sub_7();
extern  float * sub_7_svc();
#define MUL 3
extern  float * mul_7();
extern  float * mul_7_svc();
#define DIV 4
extern  float * div_7();
extern  float * div_7_svc();
#define POW 5
extern  float * pow_7();
extern  float * pow_7_svc();
extern int compute_7_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
